# compute features about attention patterns

this relies on the activations computed with `make am-activations`

In [1]:
from pathlib import Path

import muutils.tensor_info
import polars as pl

# attention-motifs
from attention_motifs.features.analysis import null_stats
from attention_motifs.features.features import (
	compute_scalar_features,
	scalar_feature_table,
)

In [2]:
# colored tensor info
muutils.tensor_info.DEFAULT_SETTINGS["colored"] = True
# numbers of rows to display
pl.Config.set_tbl_rows(10)
# base paths
PATH_BASE: Path = Path("../data/features/")
PATH_FIGURES: Path = Path("figures/")

# run feature gen

if you change things here or in the activation generation, then in notebook 02 change the filename to the one printed at the end of this cell

In [3]:
DATA_RAW: pl.DataFrame = scalar_feature_table(
	act_path=Path("../docs/"),
	features_func=compute_scalar_features,
	# models=["pythia-14m", "tiny-stories-1M"],
	out_path=PATH_BASE,
)

models: ['gpt2-small', 'pythia-1b']
model 1/2: 'gpt2-small'
✔️  (0.00s) setting up paths
✔️  (0.00s) loading prompts
16 prompts loaded
using 16 processes

100%|██████████| 16/16 [00:11<00:00,  1.35it/s]

model 2/2: 'pythia-1b'
✔️  (0.00s) setting up paths
| (0.00s) loading prompts

✔️  (0.00s) loading prompts
16 prompts loaded
using 16 processes

100%|██████████| 16/16 [00:08<00:00,  1.84it/s]

output shape: (4352, 101)
saving to ../data/features/raw-m2-p16-c101.jsonl

# save raw data

In [4]:
# uncomment and run to load raw data from file instead of regenerating
# DATA_RAW = pl.read_ndjson(PATH_BASE / "some-path.jsonl")

# basic data inspection

In [5]:
DATA_RAW

shape: (4_352, 101)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ activatio ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ n.model   ┆ n.layer   ┆ n.cache_k ┆ n.head    ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ ---       ┆ ---       ┆ ey        ┆ ---       ┆   ┆ .hist.psd ┆ .hist.lin ┆ .hist.lin ┆ ew.hist. │
│ str       ┆ i64       ┆ ---       ┆ i64       ┆   ┆ _to…      ┆ reg…      ┆ reg…      ┆ linreg…  │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 0         ┆ … ┆ 25.282935 ┆ -0.08209  ┆ 2.227927  ┆ 0.041854 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 1         ┆ … ┆ 25.151185 ┆ -0.083297 ┆ 2.231593  ┆ 0.042928 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 2         ┆ … ┆ 24.849602 ┆ -0.082528 ┆ 2.231345  ┆ 0.042285 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 3         ┆ … ┆ 16.040059 ┆ -0.079968 ┆ 2.416247  ┆ 0.040541 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 4         ┆ … ┆ 36.71329  ┆ -0.1465   ┆ 3.933273  ┆ 0.138092 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ pythia-1b ┆ 15        ┆ blocks.15 ┆ 3         ┆ … ┆ 28.71689  ┆ -0.096811 ┆ 2.589577  ┆ 0.045365 │
│           ┆           ┆ .attn.hoo ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k_pattern ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-1b ┆ 15        ┆ blocks.15 ┆ 4         ┆ … ┆ 30.042437 ┆ -0.097363 ┆ 2.581897  ┆ 0.045734 │
│           ┆           ┆ .attn.hoo ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k_pattern ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-1b ┆ 15        ┆ blocks.15 ┆ 5         ┆ … ┆ 23.794731 ┆ -0.09892  ┆ 2.727313  ┆ 0.047855 │
│           ┆           ┆ .attn.hoo ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k_pattern ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-1b ┆ 15        ┆ blocks.15 ┆ 6         ┆ … ┆ 29.972103 ┆ -0.098274 ┆ 2.576952  ┆ 0.04665  │
│           ┆           ┆ .attn.hoo ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k_pattern ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-1b ┆ 15        ┆ blocks.15 ┆ 7         ┆ … ┆ 21.229023 ┆ -0.096878 ┆ 2.69162   ┆ 0.045768 │
│           ┆           ┆ .attn.hoo ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k_pattern ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
set(DATA_RAW.dtypes)

{Float64, Int64, String}

In [7]:
DATA_RAW.head()

shape: (5, 101)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ activatio ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ n.model   ┆ n.layer   ┆ n.cache_k ┆ n.head    ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ ---       ┆ ---       ┆ ey        ┆ ---       ┆   ┆ .hist.psd ┆ .hist.lin ┆ .hist.lin ┆ ew.hist. │
│ str       ┆ i64       ┆ ---       ┆ i64       ┆   ┆ _to…      ┆ reg…      ┆ reg…      ┆ linreg…  │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 0         ┆ … ┆ 25.282935 ┆ -0.08209  ┆ 2.227927  ┆ 0.041854 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 1         ┆ … ┆ 25.151185 ┆ -0.083297 ┆ 2.231593  ┆ 0.042928 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 2         ┆ … ┆ 24.849602 ┆ -0.082528 ┆ 2.231345  ┆ 0.042285 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 3         ┆ … ┆ 16.040059 ┆ -0.079968 ┆ 2.416247  ┆ 0.040541 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ gpt2-smal ┆ 0         ┆ blocks.0. ┆ 4         ┆ … ┆ 36.71329  ┆ -0.1465   ┆ 3.933273  ┆ 0.138092 │
│ l         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
DATA_RAW.describe()

shape: (9, 102)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ ---       ┆ n.model   ┆ n.layer   ┆ n.cache_k ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ str       ┆ ---       ┆ ---       ┆ ey        ┆   ┆ .hist.psd ┆ .hist.lin ┆ .hist.lin ┆ ew.hist. │
│           ┆ str       ┆ f64       ┆ ---       ┆   ┆ _to…      ┆ reg…      ┆ reg…      ┆ linreg…  │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4352      ┆ 4352.0    ┆ 4352      ┆ … ┆ 4352.0    ┆ 4352.0    ┆ 4352.0    ┆ 4352.0   │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 6.441176  ┆ null      ┆ … ┆ 27.326094 ┆ -0.085738 ┆ 2.397361  ┆ 0.037115 │
│ std       ┆ null      ┆ 4.16045   ┆ null      ┆ … ┆ 23.165216 ┆ 0.059071  ┆ 1.221225  ┆ 0.01574  │
│ min       ┆ gpt2-smal ┆ 0.0       ┆ blocks.0. ┆ … ┆ 2.082646  ┆ -0.248626 ┆ 0.857792  ┆ 0.003455 │
│           ┆ l         ┆           ┆ attn.hook ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _pattern  ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 3.0       ┆ null      ┆ … ┆ 13.576583 ┆ -0.098496 ┆ 1.609688  ┆ 0.02703  │
│ 50%       ┆ null      ┆ 6.0       ┆ null      ┆ … ┆ 17.723797 ┆ -0.061405 ┆ 1.88007   ┆ 0.033412 │
│ 75%       ┆ null      ┆ 10.0      ┆ null      ┆ … ┆ 28.784583 ┆ -0.048907 ┆ 2.689313  ┆ 0.046221 │
│ max       ┆ pythia-1b ┆ 15.0      ┆ blocks.9. ┆ … ┆ 95.293873 ┆ -0.010803 ┆ 5.941864  ┆ 0.138092 │
│           ┆           ┆           ┆ attn.hook ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ _pattern  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# print unique values for columns which start with "activations"
print(f"{DATA_RAW['activation.model'].unique() = }")

DATA_RAW['activation.model'].unique() = shape: (2,)
Series: 'activation.model' [str]
[
	"gpt2-small"
	"pythia-1b"
]

In [10]:
for col in DATA_RAW.columns:
	if col.startswith("activation"):
		print(f"{col = }")

col = 'activation.model'
col = 'activation.layer'
col = 'activation.cache_key'
col = 'activation.head'
col = 'activation.cls'
col = 'activation.prompt'
col = 'activation.n_ctx'

In [11]:
null_stats(DATA_RAW)

shape: (101, 3)
┌─────────────────────────────────┬───────────────┬──────────────┐
│ feature                         ┆ missing_count ┆ missing_frac │
│ ---                             ┆ ---           ┆ ---          │
│ str                             ┆ i64           ┆ f64          │
╞═════════════════════════════════╪═══════════════╪══════════════╡
│ activation.model                ┆ 0             ┆ 0.0          │
│ activation.layer                ┆ 0             ┆ 0.0          │
│ activation.cache_key            ┆ 0             ┆ 0.0          │
│ activation.head                 ┆ 0             ┆ 0.0          │
│ activation.cls                  ┆ 0             ┆ 0.0          │
│ …                               ┆ …             ┆ …            │
│ feat.log.gram.skew.hist.autoco… ┆ 0             ┆ 0.0          │
│ feat.log.gram.skew.hist.psd_to… ┆ 0             ┆ 0.0          │
│ feat.log.gram.skew.hist.linreg… ┆ 0             ┆ 0.0          │
│ feat.log.gram.skew.hist.linreg… ┆ 0             ┆ 0.0          │
│ feat.log.gram.skew.hist.linreg… ┆ 0             ┆ 0.0          │
└─────────────────────────────────┴───────────────┴──────────────┘